Kulwinder alex customer order history
COSC481W-2021Fall/capstone-snack-attack pull request #77
Opened 2021-12-03 00:56 UTC by kindubadhan

Alex Works on Backend And Kulwinder Works on Frontend Part to Show Customer's Order History Page. GitHub issue #72

2021-12-03 02:19 UTC, yu-zha requested changes
Please check the package-lock.json file.
It seems to upload too much stuff which is not used.
You may copy the package-lock.json file and overwrite it from the main branch.

2021-12-03 16:25 UTC, SuperRedTrain requested changes
This pull request is appropriately labelled and has the issue linked. But still have some issues:
(1) The title should be something like "impl: Chang X in Function Y"
(2) The first comment should give an accurate and detailed summary of the changes in PR. It also needs to explain why the changes were made.
(3) This pull request implements display-customer-order-history function, I think it do not need to contain commits of implementing place order function.
(4) Are codes related to manager Order_List state by redux still used to display order history? If not, could you please delete them.

2021-12-05 17:20 UTC, yu-zha approved these changes

2021-12-06 23:00 UTC, SuperRedTrain approved these changes
I have tested on my local machine. The customer order history page works well. Thank you for your efforts, Kulwinder and Alex!

2021-12-06 23:00 UTC, merged